
networks:
  default:
    name: ${APP_NETWORK}
    external: true
    driver: bridge

services:
  nginx-proxy:
    container_name: nginx-proxy
    restart: ${RESTART_POLICY}
    build:
      context: ./build/nginx-proxy-dev
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
