version: "3.5"

networks:
  default:
    name: ${APP_NETWORK}
    driver: bridge

services:
  nginx-proxy:
    restart: ${RESTART_POLICY}
    build:
      context: ./build/nginx-proxy-dev
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
