version: "3.5"

networks:
  default:
    name: ${APP_NETWORK}
    external: true

services:
  mysql-pma:
    container_name: mysql-pma
    restart: unless-stopped
    build:
      context: ./build/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-server
      - VIRTUAL_HOST=${PMA_SERVER_NAME}
      - LETSENCRYPT_HOST=${PMA_SERVER_NAME}
      - HTTPS_METHOD=noredirect
