networks:
  default:
    name: ${APP_NETWORK}
    external: true

services:
  mysql-pma:
    container_name: mysql-pma
    restart: unless-stopped
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-server
      - VIRTUAL_HOST=${PMA_SERVER_NAME}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PMA_SERVER_NAME}
      - HTTPS_METHOD=redirect
      - PMA_ABSOLUTE_URI=http://${PMA_SERVER_NAME}/